routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\Not_paidController;
use App\Http\Controllers\Admin\InqueueController;
use App\Http\Controllers\Admin\Cancel_clentsController;
use App\Http\Controllers\Admin\AdduserController;
use App\Http\Controllers\Admin\PillController;
use App\Http\Controllers\Admin\ReportController;




Route::redirect('/','/login');
Route::get('/login',    [AuthController::class,'login'])        ->name('login');
Route::post('/login',   [AuthController::class,'check_login'])  ->name('checklogin');
Route::get('/logout',   [AuthController::class,'logout'])        ->name('logout');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']], function() {

    Route::get('/',                                     [DashboardController::class,'index'])->name('dashboard');
    Route::view('/welcome','welcome');
    Route::view('/about','about')->name('about');

    Route::get('/client',                               [ClientController::class, 'index'])->name('clients.index');
    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');
    Route::post('/client/save',                         [ClientController::class,'save'])->name('client.save');
    Route::get('/client/findDistrictName',              [ClientController::class,'findDistrictName'])  ->name('client.findDistrictName');
    Route::get('/client/view/{id}',                     [ClientController::class, 'view'])->name('clients.view');
    Route::get('/client/view-services/{id}',            [ClientController::class, 'view_with_services'])->name('clients.view_with_services');

    Route::get('/service',                              [ServiceController::class, 'index'])->name('service.index');
    Route::post('/service/datatable',                   [ServiceController::class, 'getDataTable'])->name('service.datatable');
    Route::post('/service/save',                        [ServiceController::class,'save'])->name('service.save');

    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');

    Route::get('/client/make-order/{id}',               [OrderController::class, 'make_order'])->name('clients.make-order');
    Route::post('/client/make-order/{id}',              [OrderController::class, 'creat_order']);
    Route::post('/client/save-transaction/{id}',        [ClientController::class, 'save_transaction']);
    Route::get('/client/change_status/{id}/{endprocess}',[OrderController::class, 'change_status']);

    Route::post('/order/cancel/{account_id}',           [OrderController::class, 'cancel_order'])->name('order.cancel_order');
    Route::post('/order/datatable',                     [OrderController::class, 'getDataTable'])->name('order.datatable');
    Route::get('/order/print/{order_id}',                     [OrderController::class, 'print_result'])->name('order.print_result');

    Route::get('/queue/',                               [OrderController::class, 'index'])->name('queue.index');
    Route::post('/queue/datatable',                     [OrderController::class, 'getDataTable'])->name('queue.datatable');
    Route::post('/queue/save/{id}',                     [OrderController::class, 'save'])->name('queue.save');
    Route::get('/queue/diagnosis/{id}',                 [OrderController::class, 'make_diagnosis'])->name('queue.diagnosis');
    Route::POST('/queue/diagnosis/{id}',                [OrderController::class, 'creat_diagnosis']);

    Route::get('/not-paid',                             [Not_paidController::class, 'index'])->name('not_paid.index');
    Route::post('/not-paid/datatable',                  [Not_paidController::class, 'getDataTable'])->name('not_paid.datatable');
    Route::post('/not-paid/save',                       [Not_paidController::class, 'save'])->name('not_paid.save');
    Route::get('/not-paid/pay/{id}',                    [Not_paidController::class, 'make_pay'])->name('not_paid.pay');
    Route::get('/not-paid/check/{id}',                  [Not_paidController::class, 'check'])->name('not_paid.check');

    Route::get('/inprocess/',                           [InqueueController::class, 'index'])->name('inprocess.index');
    Route::post('/inprocess/datatable',                 [InqueueController::class, 'getDataTable'])->name('inprocess.datatable');

    Route::get('/cancel_clents/',                       [Cancel_clentsController::class, 'index'])->name('cancel_clents.index');
    Route::post('/cancel_clents/datatable',             [Cancel_clentsController::class, 'getDataTable'])->name('cancel_clents.datatable');

    Route::get('/profile',                              [AuthController::class,'update_pas'])   ->name('profile.index');
    Route::post('/profile',                             [AuthController::class,'check_update_pas']) ->name('checkupdatepas');

    Route::get('/add_user/',                            [AdduserController::class, 'index'])->name('add_user.index');
    Route::post('/add_user/datatable',                  [AdduserController::class, 'getDataTable'])->name('add_user.datatable');
    Route::post('/add_user/save',                       [AdduserController::class, 'save'])->name('add_user.save');

    Route::get('/pill/',                                [PillController::class, 'index'])->name('pill.index');
    Route::post('/pill/datatable',                      [PillController::class, 'getDataTable'])->name('pill.datatable');
    Route::post('/pill/save',                           [PillController::class, 'save'])->name('pill.save');
    Route::post('/pill/cargo/save',                     [PillController::class, 'cargo_save'])->name('pill.cargo_save');
    Route::get('/client/pills/{id}',                    [PillController::class, 'client_pills'])->name('pill.client_pills');
    Route::post('/client/pills/client-pill-save',       [PillController::class, 'client_pill_save'])->name('pill.client_pill_save');
    Route::post('/client/pills/datatable/{id}',         [PillController::class, 'getDataTableClientPills'])->name('pill.clientpills');
    Route::get('/client/pills/delete/{id}',             [PillController::class, 'client_pill_delete'])->name('pill.client_pill_delete');

    Route::get('/report/by-day',                         [ReportController::class, 'payments_by_date'])->name('report.payments_by_date');
});

app/Models/Pill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pill extends Model
{
    protected $table        = 'pills';
    protected $primaryKey   = 'pill_id';
    protected $fillable     = [
        'pill_name',
        'pill_price',
        'pill_quantity'
    ];
}

app/Http/Controllers/Admin/PillController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Account;
use App\Models\District;
use App\Models\Order;
use App\Models\Pill;
use App\Models\Pill_order;
use App\Models\Region;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;

class PillController extends Controller
{
    public function index()
    {
        return view('admin.pill.index');
    }

    public function getDataTable(Request $request)
    {
        $model = Pill::query()->orderBy('created_at','desc');
        return DataTables::eloquent($model)
            ->addIndexColumn()
            ->addColumn('action',function ($item){
                $result = '';
                if (in_array(8,Auth::user()->user_permissions)) {
                    $result .= " <button type='button' onclick=\"add_cargo(".$item->pill_id.",'".addslashes($item->pill_name)."')\" class='btn btn-primary'><span class='fa fa-plus'></span> ".__('admin.Add cargo')."</button>";
                }
                if(in_array(7,Auth::user()->user_permissions))
                {
                    $result .= " <button type='button' onclick=\"edit(".$item->pill_id.",'".addslashes($item->pill_name)."',".$item->pill_price.")\" class='btn btn-primary'><span class='fa fa-edit'></span> ".__('admin.Edit')."</button>";
                }
                return $result;
            })
            ->rawColumns(['action','status'])
            ->make(true);
    }

    public function save(Request $request)
    {
        if (!$request->has('pill_name') || $request->pill_name == "" ){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.Insert_pill_name')
            ]);
        }
        if (!$request->has('pill_price' ) || $request->pill_price == ""){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.Insert_pill_price')
            ]);
        }



        //Create or update checking
        if ($request->pill_id == 0 ){
            $d = Pill::where('pill_name','=',$request->pill_name)->first();
            if ($d != null){
                return response()->json([
                    "success"=>false,
                    "message"=>"Bunday dori oldin kiritilgan"
                ]);
            }
            //create
            $data = new Pill();
            $data->pill_name = $request->pill_name;
            $data->pill_price = $request->pill_price;
            $data->save();
        }else{
            //update
            $data = Pill::query()
                ->where('pill_id',$request->pill_id)
                ->first();
            $data->pill_name = $request->pill_name;
            $data->pill_price = $request->pill_price;
            $data->save();
        }
        return response()->json([
            "success"=>true,
            "message"=>__('admin.Data save successfully'),
        ]);

    }

    public function client_pills($account_id)
    {
        if (!in_array(6,Auth::user()->user_permissions)) {return redirect('/admin/welcome');}
        $account = Account::find($account_id);
        $region = Region::query()->where('code','=',$account->account_region_code)->first();
        $district = District::query()->where('NS10_CODE','=',$account->account_region_code)->where('code','=',$account->account_district_code)->first();
        $pills = Pill::orderBy('pill_name')->get();
        return view('admin.pill.client_pills',compact('account','region','district','pills'));
    }

    public function client_pill_save(Request $request)
    {
        if (!$request->has('pill_id') || $request->pill_id == "") {
            return response()->json([
                "success" => false,
                "message" => __('admin.Please select pill')
            ]);
        }
        if (!$request->has('quantity') || $request->quantity == "") {
            return response()->json([
                "success" => false,
                "message" => __('admin.Please insert quantity')
            ]);
        }
        $pill = Pill::find($request->pill_id);
        if ($pill->pill_quantity<$request->quantity){
            return response()->json([
                "success" => false,
                "message" => __('admin.Not enough in warehouse')
            ]);
        }

        $order              = new Pill_order();
        $order->pill_id     = $request->pill_id;
        $order->quantity    = $request->quantity;
        $order->pill_price  = $pill->pill_price;
        $order->account_id  = $request->account_id;
        $order->user_id     = Auth::user()->user_id;
        $order->save();
        $pill->pill_quantity -=$request->quantity;
        $pill->save();

        return response()->json([
            "success"=>true,
            "message"=>__('admin.Data save successfully')
        ]);
    }

    public function getDataTableClientPills(Request $request, $account_id)
    {
        $model = Pill_order::query()
            ->with(['order_pill','order_account','pill_order_user'])
            ->where('account_id','=',$account_id);
        return DataTables::eloquent($model)
            ->addColumn('action',function ($item){
                return '<button class="btn btn-danger" onclick="sweetconfirm(\''.url('/admin/client/pills/delete/'.$item->pill_id).'\')"><span class="fa fa-remove"></span> '.__('admin.Delete').'</button>';
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function client_pill_delete($id)
    {
        $pill_order = Pill_order::where('pill_id','=',$id)->first();
        $pill = Pill::find($pill_order->pill_id);
        $pill->pill_quantity +=$pill_order->quantity;
        $pill->save();
        $pill_order->delete();

        return redirect()->back();
    }

    public function cargo_save(Request $request)
    {
        if ($request->quantity == '' || $request->quantity<=0){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.Wrong data')
            ]);
        }
        $pill = Pill::find($request->pill_id);
        $order              = new Pill_order();
        $order->pill_id     = $request->pill_id;
        $order->quantity    = $request->quantity;
        $order->pill_price  = $pill->pill_price;
        $order->user_id     = Auth::user()->user_id;
        $order->save();
        $pill->pill_quantity +=$request->quantity;
        $pill->save();
        return response()->json([
            "success"=>true,
            "message"=>__('admin.Data save successfully')
        ]);
    }
}

resources/views/admin/pill/index.blade.php
@extends('admin.layouts.admin')

@section('css')
    @include('admin.layouts.datatables_css')
@endsection

@section('content')
    <div class="container-fluid m-3 pl-0 ">
        <div class="animated fadeIn">
            <div class="card card-accent-primary">
                <div class="card-header">{{__('admin.Pills')}}</div>
                <div class="card-body">
                    <div class="pull-left">
                        @if(in_array(7,\Illuminate\Support\Facades\Auth::user()->user_permissions))
                            <button class="btn btn-outline-primary" id="addBtn"><span class="fa fa-plus"></span> {{__('admin.Add_pill')}}</button>
                        @endif
                    </div>
                    <table class="table table-bordered" id="dataTable">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th> {{__('admin.Pill_name')}} </th>
                            <th> {{__('admin.Pill_price')}} </th>
                            <th> {{__('admin.Quantity')}} </th>
                            <th> {{__('admin.Action')}} </th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="accountModal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modal_title"></h4>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body" >
                    <form action="#" id="account_form">
                        @csrf
                        <input type="hidden" name="pill_id" id="pill_id" value="0">
                        <div class="form-group">
                            <label for="pill_name">{{__('admin.Pill_name')}}</label>
                            <input class="form-control" id="pill_name" name="pill_name" type="text" >
                        </div>
                        <div class="form-group">
                            <label for="pill_price">{{__('admin.Pill_price')}}</label>
                            <input class="form-control" id="pill_price" name="pill_price" type="number" >
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">{{__('admin.Close')}}</button>
                    <button class="btn btn-success" type="button" id="save_btn">{{__('admin.Save')}}</button>
                </div>
            </div>

        </div>

    </div>
    <div class="modal fade" id="cargoModal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modal_title_cargo"></h4>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body">
                    <form action="#" id="cargo_form">
                        @csrf
                        <input type="hidden" name="pill_id" id="cargo_pill_id" value="0">
                        <div class="form-group">
                            <label for="quantity">{{__('admin.Quantity')}}</label>
                            <input class="form-control" id="quantity" name="quantity" type="number" >
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">{{__('admin.Close')}}</button>
                    <button class="btn btn-success" type="button" id="save_btn_cargo">{{__('admin.Save')}}</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @include('admin.layouts.datatables_js')
    <script type="text/javascript">

        var table;
        var edit_add;
        $(document).ready(function() {
            table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('admin.pill.datatable') }}",
                    type: "POST",
                    data:{
                        "_token":"{{csrf_token()}}"
                    }
                },
                columns: [
                    {data: 'DT_RowIndex',orderable: false, searchable: false},
                    {data: 'pill_name'},
                    {data: 'pill_price'},
                    {data: 'pill_quantity'},
                    {
                        data: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });



            $('#addBtn').click(function () {
                $('#modal_title').html("{{__('admin.Add_pill')}}");
                $('#account_id').val(0);
                edit_add = 1;
                $('#pill_name').val('');
                $('#pill_price').val('');
                $('#accountModal').modal('show');
                $('#pill_name').removeClass('is-invalid');
                $('#pill_price').removeClass('is-invalid');

            })
            $('#save_btn').click(function () {
                $('#save_btn').text('Saving...'); //change button text
                $('#save_btn').attr('disabled',true); //set button enable

                var error = 0;
                if ($('#pill_name').val() === ''){
                    toastr["warning"]('{{__('admin.Insert_pill_name')}}','');
                    error = 1;
                    $('#pill_name').addClass('is-invalid')
                }else{
                    $('#pill_name').removeClass('is-invalid')
                }
                if ($('#pill_price').val() === '' ){
                    toastr["warning"]('{{__('admin.Insert_pill_price')}}','');
                    error = 1;
                    $('#pill_price').addClass('is-invalid')
                }else{
                    $('#pill_price').removeClass('is-invalid')
                }



                if (error === 0) {
                    $.ajax({
                        url : "{{route('admin.pill.save')}}",
                        type: "POST",
                        headers: {
                            'X-CSRF-TOKEN': "{{ csrf_token() }}"
                        },
                        data: $('#account_form').serialize(),
                        dataType: "JSON",
                        success: function(data)
                        {

                            if(data.success)
                            {
                                toastr["success"](data.message,'');
                                $('#accountModal').modal('hide');
                                table.ajax.reload();
                            }
                            else
                            {
                                Swal.fire({
                                    // position: 'top-end',
                                    icon: 'warning',
                                    title: data.message,
                                    showConfirmButton: false,
                                    timer: 1500
                                })

                            }
                            $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                            $('#save_btn').attr('disabled',false); //set button enable
                        },
                        error: function (jqXHR, textStatus, errorThrown)
                        {
                            Swal.fire({
                                icon: 'error',
                                title: "{{__('admin.Error server')}}",
                                showConfirmButton: false,
                                timer: 1500
                            })
                            $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                            $('#save_btn').attr('disabled',false); //set button enable
                        }
                    });
                }else{
                    $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                    $('#save_btn').attr('disabled',false);
                }


            });

            $('#save_btn_cargo').click(function () {
                $.ajax({
                    url : "{{route('admin.pill.cargo_save')}}",
                    type: "POST",
                    headers: {
                        'X-CSRF-TOKEN': "{{ csrf_token() }}"
                    },
                    data: $('#cargo_form').serialize(),
                    dataType: "JSON",
                    success: function(data)
                    {

                        if(data.success)
                        {
                            toastr["success"](data.message,'');
                            $('#cargoModal').modal('hide');
                            table.ajax.reload();
                        }
                        else
                        {
                            Swal.fire({
                                // position: 'top-end',
                                icon: 'warning',
                                title: data.message,
                                showConfirmButton: false,
                                timer: 1500
                            })

                        }
                        $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                        $('#save_btn').attr('disabled',false); //set button enable
                    },
                    error: function (jqXHR, textStatus, errorThrown)
                    {
                        Swal.fire({
                            icon: 'error',
                            title: "{{__('admin.Error server')}}",
                            showConfirmButton: false,
                            timer: 1500
                        })
                        $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                        $('#save_btn').attr('disabled',false); //set button enable
                    }
                });
            });
        } );


        function edit(id,pill_name,pill_price) {
            edit_add = 2;
            $('#modal_title').html("{{__('admin.Edit_pill')}}");
            $('#pill_id').val(id);
            $('#pill_name').val(pill_name);
            $('#pill_price').val(pill_price);
            $('#accountModal').modal('show');
            $('#pill_name').removeClass('is-invalid');
            $('#pill_price').removeClass('is-invalid');
        }

        function add_cargo(id,pill_name) {
            $('#modal_title_cargo').html("{{__('admin.Add cargo')}}: "+pill_name);
            $('#cargo_pill_id').val(id);
            $('#cargo_form').trigger('reset');
            $('#cargoModal').modal('show');
        }
    </script>
@endsection

resources/views/admin/pill/make_order.blade.php
@extends('admin.layouts.admin')

@section('css')
    @include('admin.layouts.datatables_css')
@endsection

@section('content')
    <style>
        th {
            text-align: end;
        }

    </style>
    <div class="container-fluid m-3 pl-0 ">
        <div class="animated fadeIn">
            <div class="card card-accent-primary">
                <div class="card-header"><h4 style="font-family: Georgia">{{__('admin.Add_service_for_client')}}</h4></div>
                <div class="card-body">
                    <form action="{{url('admin/client/make-order/'.$account->account_id)}}" method="POST">
                        @csrf
                        <input type="hidden" name="account_id" value="{{$account->account_id}}">
                        <div class="pull-left">
                        </div>
                        <table>
                            <tr>
                                <th>{{__('admin.Client_name')}} : </th>
                                <td> <em> {{$account->account_full_name}}</em></td>
                            </tr>
                            <tr>
                                <th> {{__('admin.Phone')}} : </th>
                                <td> <em> {{$account->account_phone}}</em></td>
                            </tr>
                            <tr>
                                <th> {{__('admin.Adress')}} : </th>
                                <td> <em>{{$region->NAME}}, {{$district->DNAME}}, {{$account->account_adress_name}}</em></td>
                            </tr>
                        </table>

                        <hr>
                        <div>
                            <fieldset class="border p-2">
                                <legend  class="w-auto" style="font-family: Georgia; color: #4a5568; size: 10px;"> {{__('admin.Servese_type')}} </legend>
                                <form>
                                    <div class="row">
                                        @foreach($services as $service)
                                            <div class="col-md-3">
                                                <div class="form-group form-check">
                                                    <input type="checkbox" class="form-check-input service" onchange="calculate_total()" name="service[]" id="{{$service->id}}" value="{{$service->id}}" data-price="{{$service->price}}">
                                                    <label class="form-check-label" style="color: navy" for="{{$service->id}}">{{$service->name}} <b>( {{number_format($service->price)}} )</b> </label>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                </form>
                            </fieldset>
                            <br>
                            <div class="pull-right">
                                <h5>{{__('admin.Total_price')}} <span id="total_sum">0</span> {{__('admin.money_type')}}</h5>
                                <button type="submit" class="btn btn-behance">Saqlash</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
<script>

    function calculate_total() {
        var total = 0;
        $("input:checked.service").each(function () {
            total+=parseInt($(this).attr('data-price'));
        });
        $('#total_sum').text(numeral(total).format('0,0'));
    }
</script>