routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\Not_paidController;
use App\Http\Controllers\Admin\InqueueController;
use App\Http\Controllers\Admin\Cancel_clentsController;
use App\Http\Controllers\Admin\AdduserController;
use App\Http\Controllers\Admin\PillController;
use App\Http\Controllers\Admin\ReportController;




Route::redirect('/','/login');
Route::get('/login',    [AuthController::class,'login'])        ->name('login');
Route::post('/login',   [AuthController::class,'check_login'])  ->name('checklogin');
Route::get('/logout',   [AuthController::class,'logout'])        ->name('logout');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']], function() {

    Route::get('/',                                     [DashboardController::class,'index'])->name('dashboard');
    Route::view('/welcome','welcome');
    Route::view('/about','about')->name('about');

    Route::get('/client',                               [ClientController::class, 'index'])->name('clients.index');
    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');
    Route::post('/client/save',                         [ClientController::class,'save'])->name('client.save');
    Route::get('/client/findDistrictName',              [ClientController::class,'findDistrictName'])  ->name('client.findDistrictName');
    Route::get('/client/view/{id}',                     [ClientController::class, 'view'])->name('clients.view');
    Route::get('/client/view-services/{id}',            [ClientController::class, 'view_with_services'])->name('clients.view_with_services');

    Route::get('/service',                              [ServiceController::class, 'index'])->name('service.index');
    Route::post('/service/datatable',                   [ServiceController::class, 'getDataTable'])->name('service.datatable');
    Route::post('/service/save',                        [ServiceController::class,'save'])->name('service.save');

    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');

    Route::get('/client/make-order/{id}',               [OrderController::class, 'make_order'])->name('clients.make-order');
    Route::post('/client/make-order/{id}',              [OrderController::class, 'creat_order']);
    Route::post('/client/save-transaction/{id}',        [ClientController::class, 'save_transaction']);
    Route::get('/client/change_status/{id}/{endprocess}',[OrderController::class, 'change_status']);

    Route::post('/order/cancel/{account_id}',           [OrderController::class, 'cancel_order'])->name('order.cancel_order');
    Route::post('/order/datatable',                     [OrderController::class, 'getDataTable'])->name('order.datatable');
    Route::get('/order/print/{order_id}',                     [OrderController::class, 'print_result'])->name('order.print_result');

    Route::get('/queue/',                               [OrderController::class, 'index'])->name('queue.index');
    Route::post('/queue/datatable',                     [OrderController::class, 'getDataTable'])->name('queue.datatable');
    Route::post('/queue/save/{id}',                     [OrderController::class, 'save'])->name('queue.save');
    Route::get('/queue/diagnosis/{id}',                 [OrderController::class, 'make_diagnosis'])->name('queue.diagnosis');
    Route::POST('/queue/diagnosis/{id}',                [OrderController::class, 'creat_diagnosis']);

    Route::get('/not-paid',                             [Not_paidController::class, 'index'])->name('not_paid.index');
    Route::post('/not-paid/datatable',                  [Not_paidController::class, 'getDataTable'])->name('not_paid.datatable');
    Route::post('/not-paid/save',                       [Not_paidController::class, 'save'])->name('not_paid.save');
    Route::get('/not-paid/pay/{id}',                    [Not_paidController::class, 'make_pay'])->name('not_paid.pay');
    Route::get('/not-paid/check/{id}',                  [Not_paidController::class, 'check'])->name('not_paid.check');

    Route::get('/inprocess/',                           [InqueueController::class, 'index'])->name('inprocess.index');
    Route::post('/inprocess/datatable',                 [InqueueController::class, 'getDataTable'])->name('inprocess.datatable');

    Route::get('/cancel_clents/',                       [Cancel_clentsController::class, 'index'])->name('cancel_clents.index');
    Route::post('/cancel_clents/datatable',             [Cancel_clentsController::class, 'getDataTable'])->name('cancel_clents.datatable');

    Route::get('/profile',                              [AuthController::class,'update_pas'])   ->name('profile.index');
    Route::post('/profile',                             [AuthController::class,'check_update_pas']) ->name('checkupdatepas');

    Route::get('/add_user/',                            [AdduserController::class, 'index'])->name('add_user.index');
    Route::post('/add_user/datatable',                  [AdduserController::class, 'getDataTable'])->name('add_user.datatable');
    Route::post('/add_user/save',                       [AdduserController::class, 'save'])->name('add_user.save');

    Route::get('/pill/',                                [PillController::class, 'index'])->name('pill.index');
    Route::post('/pill/datatable',                      [PillController::class, 'getDataTable'])->name('pill.datatable');
    Route::post('/pill/save',                           [PillController::class, 'save'])->name('pill.save');
    Route::post('/pill/cargo/save',                     [PillController::class, 'cargo_save'])->name('pill.cargo_save');
    Route::get('/client/pills/{id}',                    [PillController::class, 'client_pills'])->name('pill.client_pills');
    Route::post('/client/pills/client-pill-save',       [PillController::class, 'client_pill_save'])->name('pill.client_pill_save');
    Route::post('/client/pills/datatable/{id}',         [PillController::class, 'getDataTableClientPills'])->name('pill.clientpills');
    Route::get('/client/pills/delete/{id}',             [PillController::class, 'client_pill_delete'])->name('pill.client_pill_delete');

    Route::get('/report/by-day',                         [ReportController::class, 'payments_by_date'])->name('report.payments_by_date');
});

resources/views/admin/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Baxtli oila</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/bootstrap-datetimepicker.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/coreui.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/coreui-icons-free.css')}}">
    <link rel="shortcut icon" href="{{asset('/images/logo/logo2.png')}}" type="image/x-icon">
    <link href="{{asset('assets/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/simple-line-icons.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('assets/css/toastr.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/select2/css/select2.css')}}">


    @yield('css')
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
        <img class="navbar-brand-full" src="{{asset('/images/logo/logo2.png')}}" height="50">
        <img class="navbar-brand-minimized" src="{{asset('/images/logo/logo2.png')}}" width="30" height="30">
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link " style="margin-right: 10px" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                {{ Auth::user()->user_full_name }}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('admin.profile.index') }}">
                    <i class="fa fa-user"></i> {{__('admin.Change_password')}}</a>
                <a href="{{ url('/logout') }}" class="dropdown-item btn btn-default btn-flat">
                    <i class="fa fa-lock"></i>Logout
                </a>
                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</header>

<div class="app-body">
    @include('admin.layouts.sidebar')
    <main class="main">
        @yield('content')
    </main>
</div>
<footer class="app-footer">
    <div>
        <span>&copy; 2021 Softix.</span>
    </div>
    <div class="ml-auto">
        <span>Powered by</span>
        <a href="https://softix.uz">SOFTIX</a>
        <span>Telefon: </span>
        <a href="tel:+998975270606">+99897-(97)-527-06-06</a>

    </div>
</footer>
</body>
<!-- jQuery 3.1.1 -->
<script src="{{ asset('assets/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/moment.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap-datetimepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/coreui.min.js') }}"></script>
<script src="{{ asset('assets/js/toastr.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.maskedinput.min.js') }}"></script>
<script src="{{ asset('assets/js/numeral.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/moment-with-locales.min.js') }}"></script>
<script src="{{ asset('assets/js/sweetalert2@10.js') }}"></script>
<script src="{{ asset('assets/select2/js/select2.full.js') }}"></script>
<script>
    toastr.options = {
        "closeButton": false,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "1500",
        "hideDuration": "100",
        "timeOut": "5000",
        "extendedTimeOut": "100",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
    function sweetconfirm(url,message = '{{__('admin.Are you sure')}}') {
        Swal.fire({
            title: message,
            showDenyButton: true,
            showCancelButton: false,
            confirmButtonText:'{{__('admin.Yes')}}',
            denyButtonText:'{{__('admin.No')}}',
        }).then((result) => {
            /* Read more about isConfirmed, isDenied below */
            if (result.isConfirmed) {
                window.location = url;
            }
        })
    }
</script>
@yield('scripts')
</html>

resources/views/admin/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="{{asset('assets/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
<link rel="stylesheet" href="{{asset('assets/css/buttons.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{ asset('assets/datatables/dataTables.bootstrap4.css') }}">

resources/views/admin/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets/datatables/dataTables.bootstrap4.min.js') }}"></script>

resources/views/admin/layouts/menu.blade.php
@if(in_array(1,\Illuminate\Support\Facades\Auth::user()->user_permissions))
<li class="nav-item {{ Request::is('admin.dashboard*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('admin.dashboard') }}">
        <i class="nav-icon fa fa-dashboard"></i>
        <span>{{__('admin.Dashboard')}}</span>
    </a>
</li>
@endif
@if(in_array(2,\Illuminate\Support\Facades\Auth::user()->user_permissions))
<li class="nav-item {{ Request::is('admin.clients*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('admin.clients.index') }}">
        <i class="nav-icon fa fa-users"></i>
        <span> {{__('admin.Clients')}}</span>
    </a>
</li>
@endif
@if(in_array(7,\Illuminate\Support\Facades\Auth::user()->user_permissions))
<li class="nav-item {{ Request::is('admin.pill*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('admin.pill.index') }}">
        <i class="nav-icon fa fa-users"></i>
        <span> {{__('admin.Pills')}}</span>
    </a>
</li>
@endif
@if(in_array(4,\Illuminate\Support\Facades\Auth::user()->user_permissions) || in_array(5,\Illuminate\Support\Facades\Auth::user()->user_permissions) || in_array(10,\Illuminate\Support\Facades\Auth::user()->user_permissions))
<li class="nav-item {{ Request::is('admin.service*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('admin.queue.index') }}">
        <i class="nav-icon fa fa-file"></i>
        <span> {{__('admin.queue')}}</span>
    </a>
</li>
@endif

{{--<li class="nav-item {{ Request::is('admin.service*') ? 'active' : '' }}">--}}
{{--    <a class="nav-link" href="{{ route('admin.inprocess.index') }}">--}}
{{--        <i class="nav-icon fa fa-eye"></i>--}}
{{--        <span> {{__('admin.inprocess')}}</span>--}}
{{--    </a>--}}
{{--</li>--}}

{{--<li class="nav-item {{ Request::is('admin.service*') ? 'active' : '' }}">--}}
{{--    <a class="nav-link" href="{{ route('admin.cancel_clents.index') }}">--}}
{{--        <i class="nav-icon fa fa-remove"></i>--}}
{{--        <span> {{__('admin.Cancel_services')}}</span>--}}
{{--    </a>--}}
{{--</li>--}}

{{--<li class="nav-item {{ Request::is('admin.service*') ? 'active' : '' }}">--}}
{{--    <a class="nav-link" href="{{ route('admin.not_paid.index') }}">--}}
{{--        <i class="nav-icon fa fa-money"></i>--}}
{{--        <span> {{__('admin.not_paid')}}</span>--}}
{{--    </a>--}}
{{--</li>--}}

@if(in_array(10,\Illuminate\Support\Facades\Auth::user()->user_permissions))
    <li class="nav-item {{ Request::is('admin.service*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('admin.service.index') }}">
            <i class="nav-icon fa fa-gear"></i>
            <span> {{__('admin.Services')}}</span>
        </a>
    </li>

    <li class="nav-item {{ Request::is('admin.service*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('admin.add_user.index') }}">
            <i class="nav-icon fa fa-plus"></i>
            <span> {{__('admin.Add_user')}}</span>
        </a>
    </li>
@endif
<li class="nav-item {{ Request::is('admin.about') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('admin.about') }}">
        <i class="nav-icon fa fa-star"></i>
        <span> {{__('admin.about')}}</span>
    </a>
</li>

resources/views/admin/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            @include('admin.layouts.menu')
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>