routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\Not_paidController;
use App\Http\Controllers\Admin\InqueueController;
use App\Http\Controllers\Admin\Cancel_clentsController;
use App\Http\Controllers\Admin\AdduserController;
use App\Http\Controllers\Admin\PillController;
use App\Http\Controllers\Admin\ReportController;




Route::redirect('/','/login');
Route::get('/login',    [AuthController::class,'login'])        ->name('login');
Route::post('/login',   [AuthController::class,'check_login'])  ->name('checklogin');
Route::get('/logout',   [AuthController::class,'logout'])        ->name('logout');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']], function() {

    Route::get('/',                                     [DashboardController::class,'index'])->name('dashboard');
    Route::view('/welcome','welcome');
    Route::view('/about','about')->name('about');

    Route::get('/client',                               [ClientController::class, 'index'])->name('clients.index');
    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');
    Route::post('/client/save',                         [ClientController::class,'save'])->name('client.save');
    Route::get('/client/findDistrictName',              [ClientController::class,'findDistrictName'])  ->name('client.findDistrictName');
    Route::get('/client/view/{id}',                     [ClientController::class, 'view'])->name('clients.view');
    Route::get('/client/view-services/{id}',            [ClientController::class, 'view_with_services'])->name('clients.view_with_services');

    Route::get('/service',                              [ServiceController::class, 'index'])->name('service.index');
    Route::post('/service/datatable',                   [ServiceController::class, 'getDataTable'])->name('service.datatable');
    Route::post('/service/save',                        [ServiceController::class,'save'])->name('service.save');

    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');

    Route::get('/client/make-order/{id}',               [OrderController::class, 'make_order'])->name('clients.make-order');
    Route::post('/client/make-order/{id}',              [OrderController::class, 'creat_order']);
    Route::post('/client/save-transaction/{id}',        [ClientController::class, 'save_transaction']);
    Route::get('/client/change_status/{id}/{endprocess}',[OrderController::class, 'change_status']);

    Route::post('/order/cancel/{account_id}',           [OrderController::class, 'cancel_order'])->name('order.cancel_order');
    Route::post('/order/datatable',                     [OrderController::class, 'getDataTable'])->name('order.datatable');
    Route::get('/order/print/{order_id}',                     [OrderController::class, 'print_result'])->name('order.print_result');

    Route::get('/queue/',                               [OrderController::class, 'index'])->name('queue.index');
    Route::post('/queue/datatable',                     [OrderController::class, 'getDataTable'])->name('queue.datatable');
    Route::post('/queue/save/{id}',                     [OrderController::class, 'save'])->name('queue.save');
    Route::get('/queue/diagnosis/{id}',                 [OrderController::class, 'make_diagnosis'])->name('queue.diagnosis');
    Route::POST('/queue/diagnosis/{id}',                [OrderController::class, 'creat_diagnosis']);

    Route::get('/not-paid',                             [Not_paidController::class, 'index'])->name('not_paid.index');
    Route::post('/not-paid/datatable',                  [Not_paidController::class, 'getDataTable'])->name('not_paid.datatable');
    Route::post('/not-paid/save',                       [Not_paidController::class, 'save'])->name('not_paid.save');
    Route::get('/not-paid/pay/{id}',                    [Not_paidController::class, 'make_pay'])->name('not_paid.pay');
    Route::get('/not-paid/check/{id}',                  [Not_paidController::class, 'check'])->name('not_paid.check');

    Route::get('/inprocess/',                           [InqueueController::class, 'index'])->name('inprocess.index');
    Route::post('/inprocess/datatable',                 [InqueueController::class, 'getDataTable'])->name('inprocess.datatable');

    Route::get('/cancel_clents/',                       [Cancel_clentsController::class, 'index'])->name('cancel_clents.index');
    Route::post('/cancel_clents/datatable',             [Cancel_clentsController::class, 'getDataTable'])->name('cancel_clents.datatable');

    Route::get('/profile',                              [AuthController::class,'update_pas'])   ->name('profile.index');
    Route::post('/profile',                             [AuthController::class,'check_update_pas']) ->name('checkupdatepas');

    Route::get('/add_user/',                            [AdduserController::class, 'index'])->name('add_user.index');
    Route::post('/add_user/datatable',                  [AdduserController::class, 'getDataTable'])->name('add_user.datatable');
    Route::post('/add_user/save',                       [AdduserController::class, 'save'])->name('add_user.save');

    Route::get('/pill/',                                [PillController::class, 'index'])->name('pill.index');
    Route::post('/pill/datatable',                      [PillController::class, 'getDataTable'])->name('pill.datatable');
    Route::post('/pill/save',                           [PillController::class, 'save'])->name('pill.save');
    Route::post('/pill/cargo/save',                     [PillController::class, 'cargo_save'])->name('pill.cargo_save');
    Route::get('/client/pills/{id}',                    [PillController::class, 'client_pills'])->name('pill.client_pills');
    Route::post('/client/pills/client-pill-save',       [PillController::class, 'client_pill_save'])->name('pill.client_pill_save');
    Route::post('/client/pills/datatable/{id}',         [PillController::class, 'getDataTableClientPills'])->name('pill.clientpills');
    Route::get('/client/pills/delete/{id}',             [PillController::class, 'client_pill_delete'])->name('pill.client_pill_delete');

    Route::get('/report/by-day',                         [ReportController::class, 'payments_by_date'])->name('report.payments_by_date');
});

app/Http/Controllers/Admin/AdduserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Account;
use App\Models\District;
use App\Models\Order;
use App\Models\Region;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\Facades\DataTables;

class AdduserController extends Controller
{
    public function index()
    {
        $user = User::find(Auth::user()->user_id);
        return view('admin.add_user.index',compact('user'));
    }

    public function getDataTable(Request $request)
    {
        $model = User::query();
        return DataTables::eloquent($model)
            ->addIndexColumn()
            ->addColumn('action',function ($item){
                return "<button class='btn btn-success' onclick=\"edit(".$item->user_id.",'".addslashes($item->user_full_name)."','".addslashes($item->user_login)."','".addslashes($item->user_role_id)."')\"><span class='fa fa-pencil'></span></button>";            })
            ->rawColumns(['action'])
            ->make(true);
    }


    public function save(Request $request)
    {
        if (!$request->has('user_full_name') || $request->user_full_name == "" ){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.Enter_user_full_name')
            ]);
        }
        if (!$request->has('user_login' ) || $request->user_login == ""){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.Enter_login')
            ]);
        }
        if (!$request->has('user_password') || $request->user_password == ""){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.User_password')
            ]);
        }
        if (!$request->has('user_conforim_password') || $request->user_conforim_password == ""){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.Conforim_new_password')
            ]);
        }
        if ($request->user_conforim_password != $request->user_password){
            return response()->json([
                "success"=>false,
                "message"=>__('admin.Not_match_password')
            ]);
        }


        if ($request->user_id == 0 ){
            $data = new User();
            $data->user_full_name = $request->user_full_name;
            $data->user_login = $request->user_login;
            $data->user_password = bcrypt($request->user_password);
            $data->save();
            return response()->json([
                "success"=>true,
                "message"=>__('admin.New_user_added'),
                "user_id"=>$data->user_id
            ]);
        }
    }
}

resources/views/admin/add_user/index.blade.php
@extends('admin.layouts.admin')

@section('css')
    @include('admin.layouts.datatables_css')
@endsection

@section('content')
    <div class="container-fluid m-3 pl-0 ">
        <div class="animated fadeIn">
            <div class="card card-accent-primary">
                <div class="card-header">{{__('admin.Add_user')}}</div>
                <div class="card-body">
                    <div class="pull-left">
                        <button class="btn btn-outline-primary" id="addBtn"><span class="fa fa-plus"></span> {{__('admin.Add_user')}}</button>
                    </div>
                    <table class="table table-bordered" id="dataTable">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th> {{__('admin.User_full_name')}} </th>
                            <th> {{__('admin.User_login')}}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="accountModal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modal_title"></h4>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body">
                    <form action="#" id="account_form">
                        @csrf
                        <input type="hidden" name="user_id" id="account_id" value="0">
                        <div class="form-group">
                            <label for="company"> {{__('admin.User_full_name')}} :</label>
                            <input class="form-control" id="user_full_name" name="user_full_name"  type="text" >
                        </div>
                        <div class="form-group">
                            <label for="company">{{__('admin.User_login')}} : </label>
                            <input class="form-control" id="user_login" name="user_login" type="text" >
                        </div>

                        <div class="form-group">
                            <label for="company">{{__('admin.Parol')}} :</label>
                            <input class="form-control" id="user_password" name="user_password"  type="password" >
                        </div>
                        <div class="form-group">
                            <label for="company">{{__('admin.Conforim_password')}} :</label>
                            <input class="form-control" id="user_conforim_password" name="user_conforim_password" type="password" >
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">{{__('admin.Close')}}</button>
                    <button class="btn btn-success" type="button" id="save_btn">{{__('admin.Save')}}</button>
                </div>
            </div>

        </div>

    </div>
@endsection

@section('scripts')
    @include('admin.layouts.datatables_js')
    <script type="text/javascript">


        var table;
        var edit_add;
        $(document).ready(function() {

            table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                order: [[ 1, 'asc' ]],
                ajax: {
                    url: "{{ route('admin.add_user.datatable') }}",
                    type: "POST",
                    data:{
                        "_token":"{{csrf_token()}}"
                    }
                },
                columns: [
                    {data: 'DT_RowIndex',orderable: false, searchable: false},
                    {data: 'user_full_name'},
                    {data: 'user_login'},
                ]
            });



            $('#addBtn').click(function () {
                $('#modal_title').html("{{__('admin.Add_user')}}");
                $('#user_id').val(0);
                $('#user_full_name').val('');
                $('#user_login').val('');
                $('#accountModal').modal('show');
                $('#user_full_name').removeClass('is-invalid')
                $('#user_login').removeClass('is-invalid')

            })
            $('#save_btn').click(function () {
                $('#save_btn').text('Saving...'); //change button text
                $('#save_btn').attr('disabled',true); //set button enable

                var error = 0;
                if ($('#user_full_name').val() === ''){
                    toastr["warning"]('{{__('admin.Enter_user_full_name')}}','');
                    error = 1;
                    $('#user_full_name').addClass('is-invalid')
                }else{
                    $('#user_full_name').removeClass('is-invalid')
                }

                if ($('#user_login').val() === '' ){
                    toastr["warning"]('{{__('admin.Enter_login')}}','');
                    error = 1;
                    $('#user_login').addClass('is-invalid')
                }else{
                    $('#user_login').removeClass('is-invalid')
                }

                if ($('#user_password').val() === ''){
                    toastr["warning"]('{{__('admin.User_password')}}','');
                    error = 1;
                    $('#user_password').addClass('is-invalid')
                }else{
                    $('#user_password').removeClass('is-invalid')
                }

                if ($('#user_conforim_password').val() === ''){
                    toastr["warning"]('{{__('admin.Conforim_new_password')}}','');
                    error = 1;
                    $('#user_conforim_password').addClass('is-invalid')
                }else{
                    $('#user_conforim_password').removeClass('is-invalid')
                }



                if (error === 0) {
                    $.ajax({
                        url : "{{route('admin.add_user.save')}}",
                        type: "POST",
                        headers: {
                            'X-CSRF-TOKEN': "{{ csrf_token() }}"
                        },
                        data: $('#account_form').serialize(),
                        dataType: "JSON",
                        success: function(data)
                        {
                            if(data.success)
                            {
                                toastr["success"](data.message,'');
                                $('#accountModal').modal('hide');
                                if (edit_add == 1){
                                    window.location="{{url('/admin/add_user/index')}}/"+data.user_id;
                                }else{
                                    table.ajax.reload();
                                }
                            }
                            else
                            {
                                Swal.fire({
                                    // position: 'top-end',
                                    icon: 'warning',
                                    title: data.message,
                                    showConfirmButton: false,
                                    timer: 1500
                                })

                            }


                            $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                            $('#save_btn').attr('disabled',false); //set button enable
                        },
                        error: function (jqXHR, textStatus, errorThrown)
                        {
                            Swal.fire({
                                icon: 'error',
                                title: "{{__('admin.Error_server')}}",
                                showConfirmButton: false,
                                timer: 1500
                            })
                            $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                            $('#save_btn').attr('disabled',false); //set button enable
                        }
                    });
                }else{
                    $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                    $('#save_btn').attr('disabled',false);
                }


            });
        } );


        function edit(id,user_full_name,user_login) {
            $('#modal_title').html("{{__('admin.Edit_user_info')}}");
            $('#user_id').val(id);
            $('#user_full_name').val(user_full_name);
            $('#user_login').val(user_login);

            $('#accountModal').modal('show');
            $('#user_full_name').removeClass('is-invalid')
            $('#user_login').removeClass('is-invalid')
        }
    </script>
@endsection