routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\Not_paidController;
use App\Http\Controllers\Admin\InqueueController;
use App\Http\Controllers\Admin\Cancel_clentsController;
use App\Http\Controllers\Admin\AdduserController;
use App\Http\Controllers\Admin\PillController;
use App\Http\Controllers\Admin\ReportController;




Route::redirect('/','/login');
Route::get('/login',    [AuthController::class,'login'])        ->name('login');
Route::post('/login',   [AuthController::class,'check_login'])  ->name('checklogin');
Route::get('/logout',   [AuthController::class,'logout'])        ->name('logout');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']], function() {

    Route::get('/',                                     [DashboardController::class,'index'])->name('dashboard');
    Route::view('/welcome','welcome');
    Route::view('/about','about')->name('about');

    Route::get('/client',                               [ClientController::class, 'index'])->name('clients.index');
    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');
    Route::post('/client/save',                         [ClientController::class,'save'])->name('client.save');
    Route::get('/client/findDistrictName',              [ClientController::class,'findDistrictName'])  ->name('client.findDistrictName');
    Route::get('/client/view/{id}',                     [ClientController::class, 'view'])->name('clients.view');
    Route::get('/client/view-services/{id}',            [ClientController::class, 'view_with_services'])->name('clients.view_with_services');

    Route::get('/service',                              [ServiceController::class, 'index'])->name('service.index');
    Route::post('/service/datatable',                   [ServiceController::class, 'getDataTable'])->name('service.datatable');
    Route::post('/service/save',                        [ServiceController::class,'save'])->name('service.save');

    Route::post('/client/datatable',                    [ClientController::class, 'getDataTable'])->name('clients.datatable');

    Route::get('/client/make-order/{id}',               [OrderController::class, 'make_order'])->name('clients.make-order');
    Route::post('/client/make-order/{id}',              [OrderController::class, 'creat_order']);
    Route::post('/client/save-transaction/{id}',        [ClientController::class, 'save_transaction']);
    Route::get('/client/change_status/{id}/{endprocess}',[OrderController::class, 'change_status']);

    Route::post('/order/cancel/{account_id}',           [OrderController::class, 'cancel_order'])->name('order.cancel_order');
    Route::post('/order/datatable',                     [OrderController::class, 'getDataTable'])->name('order.datatable');
    Route::get('/order/print/{order_id}',                     [OrderController::class, 'print_result'])->name('order.print_result');

    Route::get('/queue/',                               [OrderController::class, 'index'])->name('queue.index');
    Route::post('/queue/datatable',                     [OrderController::class, 'getDataTable'])->name('queue.datatable');
    Route::post('/queue/save/{id}',                     [OrderController::class, 'save'])->name('queue.save');
    Route::get('/queue/diagnosis/{id}',                 [OrderController::class, 'make_diagnosis'])->name('queue.diagnosis');
    Route::POST('/queue/diagnosis/{id}',                [OrderController::class, 'creat_diagnosis']);

    Route::get('/not-paid',                             [Not_paidController::class, 'index'])->name('not_paid.index');
    Route::post('/not-paid/datatable',                  [Not_paidController::class, 'getDataTable'])->name('not_paid.datatable');
    Route::post('/not-paid/save',                       [Not_paidController::class, 'save'])->name('not_paid.save');
    Route::get('/not-paid/pay/{id}',                    [Not_paidController::class, 'make_pay'])->name('not_paid.pay');
    Route::get('/not-paid/check/{id}',                  [Not_paidController::class, 'check'])->name('not_paid.check');

    Route::get('/inprocess/',                           [InqueueController::class, 'index'])->name('inprocess.index');
    Route::post('/inprocess/datatable',                 [InqueueController::class, 'getDataTable'])->name('inprocess.datatable');

    Route::get('/cancel_clents/',                       [Cancel_clentsController::class, 'index'])->name('cancel_clents.index');
    Route::post('/cancel_clents/datatable',             [Cancel_clentsController::class, 'getDataTable'])->name('cancel_clents.datatable');

    Route::get('/profile',                              [AuthController::class,'update_pas'])   ->name('profile.index');
    Route::post('/profile',                             [AuthController::class,'check_update_pas']) ->name('checkupdatepas');

    Route::get('/add_user/',                            [AdduserController::class, 'index'])->name('add_user.index');
    Route::post('/add_user/datatable',                  [AdduserController::class, 'getDataTable'])->name('add_user.datatable');
    Route::post('/add_user/save',                       [AdduserController::class, 'save'])->name('add_user.save');

    Route::get('/pill/',                                [PillController::class, 'index'])->name('pill.index');
    Route::post('/pill/datatable',                      [PillController::class, 'getDataTable'])->name('pill.datatable');
    Route::post('/pill/save',                           [PillController::class, 'save'])->name('pill.save');
    Route::post('/pill/cargo/save',                     [PillController::class, 'cargo_save'])->name('pill.cargo_save');
    Route::get('/client/pills/{id}',                    [PillController::class, 'client_pills'])->name('pill.client_pills');
    Route::post('/client/pills/client-pill-save',       [PillController::class, 'client_pill_save'])->name('pill.client_pill_save');
    Route::post('/client/pills/datatable/{id}',         [PillController::class, 'getDataTableClientPills'])->name('pill.clientpills');
    Route::get('/client/pills/delete/{id}',             [PillController::class, 'client_pill_delete'])->name('pill.client_pill_delete');

    Route::get('/report/by-day',                         [ReportController::class, 'payments_by_date'])->name('report.payments_by_date');
});

resources/views/admin/queue/diagnosis.blade.php
@extends('admin.layouts.admin')

@section('css')
    @include('admin.layouts.datatables_css')
@endsection

@section('content')
    <style>
        th {
            text-align: end;
        }
    </style>
    <div class="container-fluid m-3 pl-0 ">
        <div class="animated fadeIn">
            <div class="card card-accent-primary">
                <div class="card-header"><h4 style="font-family: Georgia">{{__('admin.Client_section')}}</h4></div>
                <div >
                    <button type="button" onclick="sweetconfirm('/admin/client/change_status/{{$order->id}}/endprocess')"  class="btn btn-outline-danger" style="margin-top: 10px; margin-left: 10px;" align="right"><span class="fa fa-remove"></span> {{__('admin.End_diagnosis')}} </button>
                    <a href="{{url('/admin/client/make-order/'.$order->account_id)}}" class="btn btn-outline-success" style="margin-top: 10px; margin-left: 10px;" align="right"><span class="cil cil-loop"></span> {{__('admin.add_queue')}}</a>
                </div>
                <div class="card-body">
                    <form action="{{url('admin/queue/save/'.$order->id)}}" method="POST" id="formdiagnosis">
                        @csrf
                        <div class="pull-left">
                        </div>
                        <table>
                            <tr>
                                <th>{{__('admin.Client_name')}} : </th>
                                <td> <em> {{$account->account_full_name}}</em></td>
                            </tr>
                            <tr>
                                <th> {{__('admin.Phone')}} : </th>
                                <td> <em> {{$account->account_phone}}</em></td>
                            </tr>
                            <tr>
                                <th> {{__('admin.Adress')}} : </th>
                                <td> <em>{{$region->NAME}}, {{$district->DNAME}}, {{$account->account_adress_name}}</em></td>
                            </tr>
                        </table>

                        <hr>
                        <div>
                            <select name="result_template_id" id="result_templates">
                                <option value="0" data-template=""  >{{__('admin.Not selected')}}</option>
                                @foreach($result_templates as $item)
                                    <option value="{{$item->id}}" {{$item->id==$order->result_template_id?"selected":""}} data-template="{{addslashes($item->template)}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <hr>
                        <div>
                            <fieldset class="border p-2">
                                <legend  class="w-auto" style="font-family: Georgia; color: #4a5568; size: 10px;"> {{__('admin.Write_diagnosis')}} </legend>
                                <div class="form-group">
                                    <textarea class="form-control" id="diagnosis" name="diagnosis" rows="10"  type="text" >{!! $order->diagnosis !!}</textarea>
                                </div>
                            </fieldset>
                            <br>
                            <div class="pull-right">
                                <button type="button" id="save_btn" class="btn btn-behance">{{__('admin.Save')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <style>

    </style>
@endsection
@section('scripts')
    @include('admin.layouts.datatables_js')
    <script src="{{asset('tinymce/tinymce.min.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            tinymce.init({
                force_br_newlines : true,
                force_p_newlines : false,
                forced_root_block : '',
                selector: "textarea",
                content_css: [
                    '{{asset('assets/css/table.css')}}'
                ],
                theme: "modern",
                plugins: [
                    "advlist autolink link image lists charmap print preview hr anchor pagebreak",
                    "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
                    "table contextmenu directionality emoticons paste textcolor responsivefilemanager code"
                ],
                toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent ",
                toolbar2: "print preview code ",
                image_advtab: true ,
                external_filemanager_path:"/filemanager/",
                filemanager_title:"Responsive Filemanager" ,
                external_plugins: { "filemanager" : "/filemanager/plugin.min.js"}
            });
            $('#result_templates').on('change',function () {
                tinymce.get('diagnosis').setContent($(this).find(':selected').data('template'));
            });

            $('#save_btn').click(function () {
                $('#save_btn').text('Saving...'); //change button text
                $('#save_btn').attr('disabled',true); //set button enable

                var error = 0;
                if ($('#diagnosis').val() === ''){
                    toastr["warning"]('{{__('admin.Please_write_diagnosis')}}','');
                    $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                    $('#save_btn').attr('disabled',false); //set button enable
                    error = 1;
                    $('#diagnosis').addClass('is-invalid')
                }else{
                    $('#diagnosis').removeClass('is-invalid')
                }


                if (error === 0) {
                    $('#diagnosis').val(tinymce.get('diagnosis').getContent());
                    $.ajax({
                        url : "{{route('admin.queue.save', $order->id)}}",
                        type: "POST",
                        headers: {
                            'X-CSRF-TOKEN': "{{ csrf_token() }}"
                        },
                        data: $('#formdiagnosis').serialize(),
                        dataType: "JSON",
                        success: function(data)
                        {

                            if(data.success)
                            {
                                toastr["success"](data.message,'');
                                $('#serviceModal').modal('hide');
                            }
                            else
                            {
                                Swal.fire({
                                    icon: 'warning',
                                    title: data.message,
                                    showConfirmButton: false,
                                    timer: 1500
                                })
                            }
                            $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                            $('#save_btn').attr('disabled',false); //set button enable
                            table.ajax.reload();
                        },
                        error: function (jqXHR, textStatus, errorThrown)
                        {
                            Swal.fire({
                                icon: 'error',
                                title: "{{__('admin.Error_server')}}",
                                showConfirmButton: false,
                                timer: 1500
                            })
                            $('#save_btn').text('{{__('admin.Save')}}'); //change button text
                            $('#save_btn').attr('disabled',false); //set button enable
                            table.ajax.reload();
                        }
                    });
                }
            });
        } );



    </script>
@endsection

resources/views/admin/queue/index.blade.php
@extends('admin.layouts.admin')

@section('css')
    @include('admin.layouts.datatables_css')
@endsection

@section('content')
    <div class="container-fluid m-3 pl-0 ">
        <div class="animated fadeIn">
            <div class="card card-accent-primary">
                <div class="card-header">{{__('admin.Inqueue_clents')}}</div>
                <div class="card-body">
                    <table class="table table-bordered" id="dataTable">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>{{__('admin.Name')}}</th>
                            <th>{{__('admin.Servese_type')}}</th>
                            <th>{{__('admin.service_fee_status')}}</th>
                            <th>{{__('admin.Write_diagnosis')}}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @include('admin.layouts.datatables_js')
    <script type="text/javascript">

        var table;
        $(document).ready(function() {

            table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                order: [[1, 'asc']],
                ajax: {
                    url: "{{ route('admin.queue.datatable') }}",
                    type: "POST",
                    data: {
                        "_token": "{{csrf_token()}}"
                    }
                },
                columns: [
                    {data: 'DT_RowIndex', orderable: false, searchable: false},
                    {data: 'order_account.account_full_name'},
                    {data: 'order_service.name'},
                    {data: 'status'},
                    {
                        data: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });
        });
    </script>
@endsection